#!/bin/bash
# SPDX-FileCopyrightText: 2024 Sou Kawamoto <s23c1040mc@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

# 標準入力からデータを読み取り、大文字は小文字、小文字は大文字に変換して逆順に出力
while read line; do
    echo "$line" | tr '[:lower:][:upper:]' '[:upper:][:lower:]' | rev
done
